sudo: required
language: go

branches:
  only:
  - master
  - "/^v\\d+(\\.\\d+)+$/"

matrix:
  include:
    - go: "1.12"
      os: linux
      env: OS="linux"
    - go: "1.12"
      os: osx
      env: OS="darwin"

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin $GOLANGCILINT_VERSION
  - go get github.com/axw/gocov/gocov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-$OS-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- golangci-lint run       # run a bunch of code checkers/linters in parallel
- go test -v -race ./... -coverprofile c.out # Run all the tests with the race detector enabled

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify