sudo: required
language: go

branches:
  only:
  - master
  - "/^v\\d+(\\.\\d+)+$/"

matrix:
  include:
    - go: 1.12
      os: linux
    - go: 1.11
      os: linux
    - go: 1.10
      os: linux
    - go: 1.12
      os: windows
    - go: 1.11
      os: windows
    - go: 1.10
      os: windows
    - go: 1.12
      os: osx
    - go: 1.11
      os: osx
    - go: 1.10
      os: osx

script:
- golangci-lint run       # run a bunch of code checkers/linters in parallel
- go test -v -race ./... -coverprofile c.out # Run all the tests with the race detector enabled

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify