// Code generated by "stringer -type=ChargeStatusDetail"; DO NOT EDIT.

package client

import "fmt"

const _ChargeStatusDetail_name = "DeclinedByPayerDeclinedByPayerNotRequiredCancelByNewChargeInternalFailureExpired"

var _ChargeStatusDetail_index = [...]uint8{0, 15, 41, 58, 73, 80}

func (i ChargeStatusDetail) String() string {
	if i < 0 || i >= ChargeStatusDetail(len(_ChargeStatusDetail_index)-1) {
		return fmt.Sprintf("ChargeStatusDetail(%d)", i)
	}
	return _ChargeStatusDetail_name[_ChargeStatusDetail_index[i]:_ChargeStatusDetail_index[i+1]]
}
